ersion: '3.1'
services:
mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usrsga
      MONGO_INITDB_ROOT_PASSWORD: sgausr
    ports:
      - 27017:27017
mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: usrsga
      ME_CONFIG_MONGODB_ADMINPASSWORD: sgausr
    depends_on:
      - mongo
sga-ativos-server:
    build: .
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo